### ISSUE TITLE
La difficoltà "difficile" non viene visualizzata all'avvio del programma

### ISSUE THREAD

**Issue by AlmondFlame1287** [AlmondFlame1287/Il-gioco-del-15#2]
Se si seleziona la difficoltà "difficile" non viene eseguito nessuno passaggio all'interno della funzione, e in modalità debug del compilatore, esso si chiude completamente.

**Comment by robmelfi** [comment]
E' normalissimo
https://github.com/AlmondFlame1287/Il-gioco-del-15/blob/d7313123446433ea7e3bb9794e3faffcda0434eb/gioco15.cpp#L323-L325

la chiamata alla funzione è commentata ...
