### ISSUE TITLE
Numero fisso invece di un numero randomico

### ISSUE THREAD

**Issue by AlmondFlame1287** [AlmondFlame1287/Il-gioco-del-15#5]
Il codice all'interno del branch "prova" è stato ottimizzato, ma alla chiamata della funzione facile il numero pescato da `rand()%3 +1;` rimane 3.

**Comment by robmelfi** [comment]
Tutti questi problemi in parte dipendono da #4, oppure potrebbe dipendere da un utilizzo inappropriato di `srand(time(NULL));`, momentaneamente metti da parte la gestione randomica del gioco e concentrati su tutti i possibili scenari riproducendoli staticamente.

**Comment by AlmondFlame1287** [comment]
> Tutti questi problemi in parte dipendono da #4, oppure potrebbe dipendere da un utilizzo inappropriato di `srand(time(NULL));`, momentaneamente metti da parte la gestione randomica del gioco e concentrati su tutti i possibili scenari riproducendoli staticamente.

Alla fine ho scoperto che il computer effettivamente usa dei numeri random da 1 a 3, ma era solo ma mia incredibile sfortuna che mi dava sempre 3 o sempre 2 o sempre 1.
